version: "3.6"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "54320:54320"
  web:
    build: .
    environment: 
      - DJANGO_SETTINGS_MODULE=penzi.production_settings
    ports: 
      - "8000:8000"
    volumes:
      - .:/code
    command:
      - /bin/sh
      - '-c'
      - '/code/entrypoint.sh'
    depends_on:
      - db