version: "3.6"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
  web:
    build: .
    environment: 
      - DJANGO_SETTINGS_MODULE=penzi.production_settings
    volumes:
      - .:/code
    command:
      - /bin/sh
      - '-c'
      - '/code/entrypoint.sh'
    ports:
      - "8000:8000"
    depends_on:
      - db