# Generated by Django 3.2.4 on 2021-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210609_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destination',
            field=models.BigIntegerField(default=1234),
        ),
    ]
