# Generated by Django 3.2.4 on 2021-06-10 16:39

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_message_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, 'INCOMING'), (1, 'OUTGOING')], default=web.models.MessageType['INCOMING']),
        ),
    ]
